### PR TITLE
Adding order management

### PR DESCRIPTION
**Pull request by naren8642**
This pull request includes order management methods. You can create, edit or cancel orders. Complex orders are supported. You can also get order / account status information.

This is my first ever pull request so if there are other steps to be taken please let me know.

If these changes are acceptable I can also provide readme updates.

### CODE REVIEW

**Comment by wakproductions** [comment]
Thanks so much for your contribution Naren! Please give me a few days to look it over. Once thing I would want to change is the way the tests are conducted. I use RSpec as a testing framework. I don't like that it submits an actual order into the system to test. I would much rather create mock HTTP responses, such as with the VCR gem. 

I will need to play around with the code a bit before merging. But overall, nice work!

**Comment by naren8642** [comment]
I was also a bit leery about submitting real orders even though it was for a $1. At the same time I wanted to make sure that when I placed, edited or cancelled an order this was reflected on the TDA system. I guess once we have established that the transport layer works, we can use something like the VCR gem to test at the order level with various options. Thanks for your feedback and also for starting off this project in the first place.

**Comment by wakproductions** [comment]
So I think the balances and positions feature is good to merge, but the equity order feature needs a lot of work, especially in the area of testing. I created a new PR isolating just that one feature. https://github.com/wakproductions/tdameritrade_api/pull/4

**Comment by naren8642** [comment]
That sounds like a great idea. Thanks for doing this. If you want to give
me some pointers with regards to implementing the tests for the orders, I
can spend some time on that - mainly so I can learn that too.

Is there something I need to do with the new PR? Or is it ready to be
pulled?

**Comment by wakproductions** [comment]
@naren8642 That's what makes this tricky. We need a way of writing an RSpec test that tests the order system without submitting an actual order. Here's the good news - connectivity is already tested in all of the other tests. The main goal of a test here is to act as a _regression test_, so that if you make a change to the system in the future that breaks something you won't be taken by surprise when running it against the live system. Therefore, you can probably test the order system by stubbing and mocking. Look up the docs on RSpec and figure out a way to fake a response from the TD Ameritrade system. The important thing is that the routine you're writing interprets that response correctly - both for successful orders and in error handling.

**Comment by wakproductions** [comment]
Partial implementation of this PR in v1.1

**Pull request closed without merging**
